name: Deploy news agent to AWS ECR

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (this one)
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Run Unit Tests
        run: |
          ./mvnw test

      - name: Build maven project
        run: |
          ./mvnw clean package -DskipTests

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag Docker image
        run: |
            IMAGE_URI=${{ secrets.ECR_REGISTRY }}/personal/newsalert:latest
            docker build -t $IMAGE_URI ./headline_newsletter
            echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Push image to ECR
        run: |
          docker push $IMAGE_URI